### ISSUE TITLE
Pls Migrate to Android X

### ISSUE THREAD

**Issue by josephvijayandroiddev** [swapnil1104/PassCodeText#11]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by swapnil1104** [comment]
@josephvijayandroiddev noted. Will punish the next release with AndroidX.

**Comment by swapnil1104** [comment]
Hi @josephvijayandroiddev, I've published v0.2 with AndroidX support, you can check it out.
Closing this issue.
