### ISSUE TITLE
Attribute hint is not applied well

### ISSUE THREAD

**Issue by ShangOh** [swapnil1104/PassCodeText#15]
**Describe the bug**
I've added below text in xml file but the hint text does not appear.
android:hint="12345"

**To Reproduce**
Set hint text in OtpEditText

**Expected behavior**
The hint text '12345' should be shown.

**Comment by swapnil1104** [comment]
Yes, this is a known issue. Will fix this in the next release.

**Comment by swapnil1104** [comment]
Hi @ShangOh thanks a lot for filing the issue. 
The issue has been fixed and the PR is raised, please check and let me know if there are any concerns, will raise merge the PR and release a new version 
EOD tomorrow 

https://github.com/swapnil1104/PassCodeText/blob/hint_support/images/hint.gif

**Comment by swapnil1104** [comment]
@ShangOh Please use the latest release
