### ISSUE TITLE
!mHintText.isEmpty() causes a crash

### ISSUE THREAD

**Issue by greatflag** [swapnil1104/PassCodeText#17]
Hi, it is a useful widget. but must add `android:hint=""` to the xml file,  or application will crash. 
`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
        at com.broooapps.otpedittext2.OtpEditText.onDraw(OtpEditText.java:231)`

**Comment by swapnil1104** [comment]
@greatflag the issue has been fixed in the latest rc release tag. Please check.
