### ISSUE TITLE
Mask input same as password field types

### ISSUE THREAD

**Issue by aaabidunique** [swapnil1104/PassCodeText#3]
Hi,
Is there a way to mask the input i.e same password fileds.
FYI, using android:inputType="numberPassword" didn't help.

**Comment by swapnil1104** [comment]
Noted.
I'll implement this functionality and push out a release ASAP.

**Comment by aaabidunique** [comment]
@swapnil1104 If possible can you add the configurable mask character, so that I can choose what is the mask character.

**Comment by swapnil1104** [comment]
I'll look into it.

**Comment by swapnil1104** [comment]
The functionality has been added with the latest release.
You can mask the character by adding  **app:oev_mask_input="true"**

If you need to use a special character, please check the documentation.
https://github.com/swapnil1104/PassCodeText#masking-input-characters-with-asterisk

I'm closing this issue, please do let me know if something there is some other enhancement that you require.

@aaabidunique
