### ISSUE TITLE
Event when user completed typing OTP

### ISSUE THREAD

**Issue by aaabidunique** [swapnil1104/PassCodeText#6]
I need to performing operation when user completes typing in the OTP field.
Can @swapnil1104 suggest me best way do?

**Comment by swapnil1104** [comment]
I'll add an interface implementation, let me know if something like 
```passCodeText.setOnCompleteListener({}) ```
would resolve your problem.

**Comment by aaabidunique** [comment]
@swapnil1104 I think that will do the job.
My only requirement is to auto submit the request if user typed all the numbers in OTP field.

P.S
Add the OTP value in the callback as well.

**Comment by swapnil1104** [comment]
Will add this in the next release and push it asap.

**Comment by swapnil1104** [comment]
I've added this feature to `0.1.3` release, do check it out, you can refer to the documentation. 
Feel free to ask, if you have any other queries.

@aaabidunique

**Comment by aaabidunique** [comment]
After adding the listener, callback is getting called 3-4 times.
Can you let me know about the same?

**Comment by swapnil1104** [comment]
Can you show how you've implemented it programmatically? It'll help me understand your problem better.

**Comment by aaabidunique** [comment]
@swapnil1104 Easiest way to reproduce will be your example app, but instead of Toast use Log to verify multiple calls.

**Comment by swapnil1104** [comment]
Got it. Will fix this ASAP. 

Edit: Unable to replicate the issue in the example app. Working is as it should be.

It could be that in your case onDraw is being invoked which triggers the callback, if you could give out bit more details it'll be helpful in rectifying the issue.
@aaabidunique

**Comment by aaabidunique** [comment]
> Got it. Will fix this ASAP.
> 
> Edit: Unable to replicate the issue in the example app. Working is as it should be.
> 
> It could be that in your case onDraw is being invoked which triggers the callback, if you could give out bit more details it'll be helpful in rectifying the issue.
> @aaabidunique

As I understand onDraw will be called multiple times based on view repaint, refresh rate, view changes in the hosted activity/fragment.
I think onDraw may not be the best place for complete listener.
Maybe something like text change listener might help but I may be wrong.
FYI If you need specific detail let me know.

**Comment by swapnil1104** [comment]
Will add a fix and push a release this satuday. @aaabidunique

**Comment by aaabidunique** [comment]
After thinking @swapnil1104, I think it may better for the user of library to implement the text watcher rather than you implementing it.
You can revert to your old codebase before complete listener and release the final version.
I will implement textwatcher at my side.
P.S
You can close this issue.

**Comment by swapnil1104** [comment]
I'm sorry I have been unable to implement a bug-free solution to what your problem statement is.
Been busy with things outside.

Implementing a TextWatcher would be quite simple as well since I'm extending the EditText class.

If that resolves your issue, please go ahead with this. I'll also implement an error-free implementation of the use-case. 
Thanks.
