### ISSUE TITLE
False triggering of OnCompleteListener

### ISSUE THREAD

**Issue by sanya5791** [swapnil1104/PassCodeText#8]
**Describe the bug**
Redundant triggering of OnCompleteListener. It happens on first number click if OtpEditText is filled with all numbers.

**Preconditions**
1. Setup OtpEditText with:
                android:clickable="false"
                android:cursorVisible="false"
                android:inputType="number"
                android:maxLength="6"
                android:textSize="@dimen/font_size_30"
                android:textStyle="bold"
                android:digits="0123456789"
2. Set OnCompleteListener with log message "OnCompleteListener triggered"

**To Reproduce**
1. Go to screen with OtpEditText
2. Click on 'OtpEditText'
3. enter 6 numbers (you can see "OnCompleteListener triggered" log message)
4. Click on 1 number of OtpEditText

**Actual behavior**
TWO row of "OnCompleteListener triggered" logging message is displayed

**Expected behavior**
ONE row of "OnCompleteListener triggered" logging message is displayed

**Smartphone (please complete the following information):**
 - Device: [Emulator Nexus 5X]
 - OS: [Android]
 - Version [9.0]

Thank you for you work!

**Comment by swapnil1104** [comment]
Yes I'm aware of this, I'll fix both the issues and push out a release as soon as possible.

**Comment by swapnil1104** [comment]
This issue has been resolved in the latest release @sanya5791 

Please check version 0.1.5
